name: Regions
version: 1.12
author: bms_
main: io.bms.biomes.BiomesMod
softdepend: [Multiverse-Core]
commands:
   loadbiomes:
      description: This command reloads the biome name configurations
      usage: /loadbiomes
      permission: biomes.loadbiomes
      permission-message: You don't have permission to run that command.
